version: '3.8'

services:

  inv-api:
    build:
      context: .
      target: ${ENV_MODE}
      dockerfile: ./docker/Node.inventories.Dockerfile
    env_file:
      - .env
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - inv-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres # TODO: dynamic val
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432' # TODO: dynamic val
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - inv-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # TODO: dynamic val
      PGADMIN_DEFAULT_PASSWORD: admin # TODO: dynamic val
    ports:
      - '5050:80' # TODO: dynamic val
    depends_on:
      - db
    networks:
      - inv-network

volumes:
  postgres-data:

networks:
  inv-network: