version: '3.8'

services:

  inv-api:
    build:
      context: .
      target: ${ENV_MODE}
      dockerfile: ./docker/Node.inventories.Dockerfile
    env_file:
      - .env
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - inv-network

  db:
    build:
      context: .
      dockerfile: ./docker/POSTGRES.inventory.dockerfile
    container_name: ${POSTGRES_SERVER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - inv-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # TODO: dynamic val
      PGADMIN_DEFAULT_PASSWORD: admin # TODO: dynamic val
    ports:
      - '5050:80' # TODO: dynamic val
    depends_on:
      - db
    networks:
      - inv-network

volumes:
  postgres-data:

networks:
  inv-network: